//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuneMax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public Account()
        {
            this.News = new HashSet<News>();
            this.ProductGroups = new HashSet<ProductGroup>();
            this.Products = new HashSet<Product>();
            this.UploadGroups = new HashSet<UploadGroup>();
            this.Uploads = new HashSet<Upload>();
            this.Sliders = new HashSet<Slider>();
        }
    
   
    
        public virtual ICollection<News> News { get; set; }
        public virtual ICollection<ProductGroup> ProductGroups { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual ICollection<UploadGroup> UploadGroups { get; set; }
        public virtual ICollection<Upload> Uploads { get; set; }
        public virtual ICollection<Slider> Sliders { get; set; }
    }
}
