//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuneMax.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.UsersBaskets = new HashSet<UsersBasket>();
            this.ShopLists = new HashSet<ShopList>();
        }
    
    
        public virtual ICollection<UsersBasket> UsersBaskets { get; set; }
        public virtual ICollection<ShopList> ShopLists { get; set; }
    }
}
