//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TuneMax.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseModelContainer : DbContext
    {
        public DatabaseModelContainer()
            : base("name=DatabaseModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> AccountSet { get; set; }
        public DbSet<NewsGroup> NewsGroupSet { get; set; }
        public DbSet<News> NewsSet { get; set; }
        public DbSet<ProductGroup> ProductGroupSet { get; set; }
        public DbSet<Product> ProductSet { get; set; }
        public DbSet<Users> UsersSet { get; set; }
        public DbSet<UsersBasket> UsersBaskets { get; set; }
        public DbSet<UploadGroup> UploadGroupSet { get; set; }
        public DbSet<Upload> UploadSet { get; set; }
        public DbSet<ShopList> ShopLists { get; set; }
        public DbSet<Comment> CommentSet { get; set; }
        public DbSet<Slider> SliderSet { get; set; }
    }
}
